### ISSUE TITLE
Add multiple application folder paths.

### ISSUE THREAD

**Issue by Fenweldryn** [smallp/vscode-ci#24]
I work with several codeigniter application folders within a project folder (with unique system folder) and I would like to add them all to the config path ("CI.app": "application",), otherwise the autocomplete does not work at all and I have to change manually the path everytime I go work on other project. 
Is it possible to add a json to the setting? For example: "CI.app": "{folder1/application,folder2/application,folder3/application}".

EDIT: just noticed you have that functionality for library and model settings.

**Comment by smallp** [comment]
Sorry, it is hard for me to add this feature. If the config of application folder is an array, I have to read all the models in all application folders. Then the cache may be overwrote. If I distinct them with application folder, it would be a huge work.
It work for library and model settings because this extension just read and parse these files, ignoring the overwriting or something else.
